import { Course } from "./types"

export const mockCourses: Course[] = [
    {
        id: "1",
        course_dept: "AADS",
        course_code: "1010",
        class_section: "01",
        course_title: "Introduction to African American and Diaspora Studies",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Student Option Grading Basis",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description:
            "Foundations of African American culture from ancient African history and through contemporary issues in the African American experience and the larger diaspora.",
        notes: null,
        status: "Open",
        capacity: "16",
        enrolled: "12",
        wl_capacity: "10",
        wl_occupied: "0",
        attributes: [
            "AXLE: Perspectives",
            "Eligible for American Studies Major",
            "Eligible for Latino/Latina Studies",
            "Next Steps Eligible",
        ],
        meeting_days: ["TR"],
        meeting_times: ["11:00a - 12:15p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Taaffe, Claudine O. (Primary)"],
    },
    {
        id: "2",
        course_dept: "CS",
        course_code: "1101",
        class_section: "01",
        course_title: "Programming and Problem Solving",
        school: "School of Engineering",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description: "Introduction to programming concepts, algorithm design, and problem-solving techniques using Python.",
        notes: null,
        status: "Open",
        capacity: "120",
        enrolled: "98",
        wl_capacity: "20",
        wl_occupied: "5",
        attributes: ["AXLE: Mathematics and Natural Sciences"],
        meeting_days: ["MWF"],
        meeting_times: ["10:20a - 11:10a"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Johnson, Sarah M. (Primary)"],
    },
    {
        id: "3",
        course_dept: "CHEM",
        course_code: "1601",
        class_section: "02",
        course_title: "General Chemistry",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "4.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "MATH 1300 or equivalent",
        description:
            "Fundamental principles of chemistry including atomic structure, bonding, stoichiometry, and thermodynamics.",
        notes: null,
        status: "Waitlist",
        capacity: "150",
        enrolled: "150",
        wl_capacity: "30",
        wl_occupied: "25",
        attributes: ["AXLE: Mathematics and Natural Sciences", "Pre-Health"],
        meeting_days: ["MWF"],
        meeting_times: ["9:10a - 10:00a"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Rodriguez, Emily A. (Primary)", "Chen, Michael (TA)"],
    },
    {
        id: "4",
        course_dept: "HIST",
        course_code: "1370",
        class_section: "01",
        course_title: "Modern European History",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description: "Political, social, and cultural developments in Europe from 1789 to present.",
        notes: null,
        status: "Open",
        capacity: "40",
        enrolled: "35",
        wl_capacity: "10",
        wl_occupied: "0",
        attributes: ["AXLE: History and Culture", "European Studies"],
        meeting_days: ["TR"],
        meeting_times: ["11:00a - 12:15p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Wilson, James P. (Primary)"],
    },
    {
        id: "5",
        course_dept: "PHYS",
        course_code: "2620",
        class_section: "01",
        course_title: "Quantum Mechanics I",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "Instructor Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "PHYS 2620, MATH 2420",
        description: "Principles of quantum mechanics and applications to atomic systems.",
        notes: null,
        status: "Open",
        capacity: "25",
        enrolled: "22",
        wl_capacity: "5",
        wl_occupied: "0",
        attributes: ["Physics Major Required"],
        meeting_days: ["MWF"],
        meeting_times: ["1:10p - 2:00p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Park, Lisa K. (Primary)"],
    },
    {
        id: "6",
        course_dept: "MATH",
        course_code: "1300",
        class_section: "03",
        course_title: "Differential and Integral Calculus",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "4.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "High school calculus or placement test",
        description: "Limits, derivatives, integrals, and applications of single-variable calculus.",
        notes: null,
        status: "Open",
        capacity: "80",
        enrolled: "72",
        wl_capacity: "15",
        wl_occupied: "3",
        attributes: ["AXLE: Mathematics and Natural Sciences", "Pre-Engineering"],
        meeting_days: ["MWF"],
        meeting_times: ["8:10a - 9:00a"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Thompson, David R. (Primary)"],
    },
    {
        id: "7",
        course_dept: "ECON",
        course_code: "1010",
        class_section: "01",
        course_title: "Principles of Microeconomics",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description:
            "Introduction to economic principles including supply and demand, market structures, and consumer behavior.",
        notes: null,
        status: "Open",
        capacity: "200",
        enrolled: "185",
        wl_capacity: "25",
        wl_occupied: "12",
        attributes: ["AXLE: Social and Behavioral Sciences", "Business Minor"],
        meeting_days: ["TR"],
        meeting_times: ["2:20p - 3:35p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Martinez, Ana L. (Primary)"],
    },
    {
        id: "8",
        course_dept: "BIOL",
        course_code: "1510",
        class_section: "01",
        course_title: "Introductory Biology",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "4.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "High school biology recommended",
        description: "Fundamental concepts in biology including cell structure, genetics, evolution, and ecology.",
        notes: null,
        status: "Waitlist",
        capacity: "180",
        enrolled: "180",
        wl_capacity: "40",
        wl_occupied: "35",
        attributes: ["AXLE: Mathematics and Natural Sciences", "Pre-Health", "Environmental Studies"],
        meeting_days: ["MWF"],
        meeting_times: ["11:10a - 12:00p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Kumar, Priya S. (Primary)", "Williams, Robert (TA)"],
    },
    {
        id: "9",
        course_dept: "ENGL",
        course_code: "1010",
        class_section: "15",
        course_title: "Writing Seminar",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Seminar",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description: "Development of critical writing skills through analysis of contemporary issues and literary texts.",
        notes: null,
        status: "Open",
        capacity: "18",
        enrolled: "16",
        wl_capacity: "5",
        wl_occupied: "0",
        attributes: ["AXLE: Writing", "First-Year Writing"],
        meeting_days: ["TR"],
        meeting_times: ["9:35a - 10:50a"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Brown, Jennifer K. (Primary)"],
    },
    {
        id: "10",
        course_dept: "PSYC",
        course_code: "1200",
        class_section: "02",
        course_title: "General Psychology",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description: "Introduction to psychological principles including learning, memory, cognition, and social behavior.",
        notes: null,
        status: "Open",
        capacity: "150",
        enrolled: "142",
        wl_capacity: "20",
        wl_occupied: "8",
        attributes: ["AXLE: Social and Behavioral Sciences", "Psychology Major"],
        meeting_days: ["MWF"],
        meeting_times: ["2:10p - 3:00p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Davis, Michael T. (Primary)"],
    },
    {
        id: "11",
        course_dept: "CS",
        course_code: "2201",
        class_section: "01",
        course_title: "Data Structures and Algorithms",
        school: "School of Engineering",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "CS 1101 or equivalent",
        description: "Advanced programming concepts including data structures, algorithms, and computational complexity.",
        notes: null,
        status: "Open",
        capacity: "100",
        enrolled: "95",
        wl_capacity: "15",
        wl_occupied: "10",
        attributes: ["CS Major Required", "Software Engineering Track"],
        meeting_days: ["TR"],
        meeting_times: ["1:10p - 2:25p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Zhang, Wei L. (Primary)"],
    },
    {
        id: "12",
        course_dept: "ART",
        course_code: "1030",
        class_section: "01",
        course_title: "Drawing Fundamentals",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Studio",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description: "Basic drawing techniques using various media including pencil, charcoal, and ink.",
        notes: null,
        status: "Open",
        capacity: "24",
        enrolled: "20",
        wl_capacity: "8",
        wl_occupied: "2",
        attributes: ["AXLE: Creative Arts", "Art Major", "Studio Art"],
        meeting_days: ["MW"],
        meeting_times: ["3:00p - 5:30p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Garcia, Sofia M. (Primary)"],
    },
    {
        id: "13",
        course_dept: "PHIL",
        course_code: "1301",
        class_section: "01",
        course_title: "Introduction to Ethics",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "",
        description: "Examination of major ethical theories and their application to contemporary moral issues.",
        notes: null,
        status: "Open",
        capacity: "35",
        enrolled: "28",
        wl_capacity: "10",
        wl_occupied: "0",
        attributes: ["AXLE: Perspectives", "Philosophy Major", "Ethics Certificate"],
        meeting_days: ["TR"],
        meeting_times: ["11:00a - 12:15p"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Anderson, Mark J. (Primary)"],
    },
    {
        id: "14",
        course_dept: "SPAN",
        course_code: "1103",
        class_section: "04",
        course_title: "Elementary Spanish",
        school: "College of Arts and Science",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "4.0",
        grading_basis: "Graded",
        consent: "No Special Consent Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "No prior Spanish experience",
        description:
            "Introduction to Spanish language and culture with emphasis on speaking, listening, reading, and writing.",
        notes: null,
        status: "Open",
        capacity: "22",
        enrolled: "19",
        wl_capacity: "5",
        wl_occupied: "1",
        attributes: ["AXLE: International Cultures", "Language Requirement"],
        meeting_days: ["MTWRF"],
        meeting_times: ["9:10a - 10:00a"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Lopez, Carmen R. (Primary)"],
    },
    {
        id: "15",
        course_dept: "MUSC",
        course_code: "1200",
        class_section: "01",
        course_title: "Music Theory I",
        school: "Blair School of Music",
        career: "Undergraduate",
        class_type: "Lecture",
        credit_hours: "3.0",
        grading_basis: "Graded",
        consent: "Audition Required",
        term_year: "2025",
        term_season: "Fall",
        session: "Regular Academic Session",
        dates: "8/20/25 - 12/4/25",
        requirements: "Music major or instructor permission",
        description: "Fundamentals of music theory including scales, intervals, chords, and basic harmonic progressions.",
        notes: null,
        status: "Closed",
        capacity: "30",
        enrolled: "30",
        wl_capacity: "10",
        wl_occupied: "10",
        attributes: ["Music Major Required", "Blair School Core"],
        meeting_days: ["MWF"],
        meeting_times: ["10:20a - 11:10a"],
        meeting_dates: ["8/20/25-12/4/25"],
        instructors: ["Taylor, Rebecca S. (Primary)"],
    },
]
